### PR TITLE
Fix/refactor/optim(StructureIconsLayer): restore structure icons after context loss, use WebGL/WebGPU/Canvas, and some improvements

### LINKED ISSUE #2147: Handle graphics context loss for PixiJS (buildings/structure icons dissapear or never appear)
Fix for eg. 'buildings and boats vanish': https://discord.com/channels/1284581928254701718/1414525013402587199/1414525013402587199

Since PR #1667, context loss is handled for Canvas. No context restore has been implemented for the PixiJS layer though. There is a function called something like handleContextLoss for this in PixiJS which was at first (confusingly) only for testing purposes, but since somewhere in 2023 it actually handles context loss like the name suggests. This should prevent some cases where structures or icons go missing from the screen.

PR 1667 notes about this "This PR represents a partial fix for the context loss issue. Specifically, the StructureIconsLayer remains in a broken state after context restoration. This layer is rendered using Pixi.js, which has its own specific process for handling renderer recovery. Due to my lack of experience with the Pixi.js API, I was unable to implement the fix for this layer. This would be an excellent follow-up contribution for someone familiar with Pixi."

See also discussion mostly about Canvas 2D here, with a mention of PixiJS: 
https://discord.com/channels/1359946986937258015/1383112688082620509/1400649645809602571

Other relevant bug reports, some with screenshots also from the console:
https://discord.com/channels/1284581928254701718/1439606494910873671/1439606494910873671

https://discord.com/channels/1284581928254701718/1431724493402800158

https://discord.com/channels/1284581928254701718/1414774471784534026

https://discord.com/channels/1284581928254701718/1414525013402587199

https://discord.com/channels/1284581928254701718/1396795776256184422

### LINKED ISSUE #3207: Incremental Pixi.js Quality Improvements for Structure Icon Rendering
## Purpose

Apply incremental, low-risk quality fixes to the Pixi.js structure icon path to improve correctness, cleanup, and maintainability without changing gameplay behavior or architecture.

---

## Objectives

- Remove O(n) render lookups by replacing array state with a unit-id keyed map in StructureIconsLayer.ts.
- Eliminate avoidable allocations (outline filters, dot graphics churn, temporary colorization canvas).
- Fix known correctness/lifecycle issues:
  - async ghost-state race
  - texture cache GPU leak on invalidation
  - inconsistent child destruction
  - missing renderer/stage disposal path
- Replace Pixi namespace import style with named imports in:
  - StructureIconsLayer.ts
  - StructureDrawingUtils.ts
- Consolidate magic numbers into named constants.

---

## Description

Scope is limited to StructureIconsLayer.ts and StructureDrawingUtils.ts, with independent incremental steps:

1. Array → map for render records keyed by unit id.
2. Reuse static red/green/white outline filters.
3. Move or stage async ghost action lookup so render reads synchronous cached state.
4. Destroy cached textures before map eviction during cache invalidation.
5. Convert to named Pixi imports.
6. Standardize container destruction with child cleanup.
7. Extract zoom/query/filter/size magic numbers into constants.
8. Ensure dot rendering assets are shared/reused consistently.
9. Add explicit dispose lifecycle (renderer, stage, cache, canvas) and hook into teardown path if available.
10. Reuse one offscreen canvas/context in image colorization helper.

Overlap / coordination:
- Complements issue #2147 (context-loss handling), especially lifecycle and texture cleanup.
- Likely low-conflict with PR #3193; both are adjacent to ghost/buildability flow.

Verification:
- Run `npm test`.
- Manual check: dot/icon/level transitions across zoom, ghost outline correctness.
- DevTools sanity: lower lingering texture count after invalidation and fewer minor GC spikes.

---

skigim

### PR DESCRIPTION
**Pull request by VariableVince**
## Description:

StructureIconsLayer and StructureDrawingUtils fixes and improvements. Most notably have it restore structure icons after webGL context loss. 

Inspired by @Skigim's https://github.com/openfrontio/OpenFrontIO/pull/3339, https://github.com/openfrontio/OpenFrontIO/pull/3480. Fixes his https://github.com/openfrontio/OpenFrontIO/issues/3207, contains only those fixes from the Issue that are actually valid and needed fixes, on top of his earlier merged PR.

### CONTAINS (partly written by AI, excuse the exaggerated language)

**1.**
* ** AutoDetectRenderer: ** now, if Hardware Acceleration is unavailable or disabled, Structure Icons will be displayed using Canvas renderer. Otherwise it will use either WebGL or WebGPU, depeding on which is available. PixiJS currently prefers WebGL but it will switch this to WebGPU at one point. We can also force it to WebGPU as explained in the comment.
* ** Canvas: ** on Canvas, what doesn't work is gracefully skipped. The non-working parts will be fixed, see this issue in their repo, but until then it will work fine for us anyway: https://github.com/pixijs/pixijs/issues/11981
* **WebGPU Context Loss:** PixiJS doesn't restore this context itself. Instead we do it by calling setupRenderer again on device loss.
* **WebGL Context Loss:** To know when we need to restore the layer, don't use native event (`webglcontextrestored`) but use PixiJS's internal hook (`this.renderer.runners.contextChange`). This prevents our cache-clearing commands from interrupting Pixi while it's still busy rebuilding its internal GL State Machine buffer. With links severed, we need to clear and rebuild all icons to restore them.
* **WebGL Context existance Check (`this.renderer.context?.isLost`):** This prevents a crash in PixiJS. Fixes black map background and all graphics frozen, which has been reported a few times. Issue created in their repo: https://github.com/pixijs/pixijs/issues/12032.
* **Redraw:** for Canvas context restore or on Alt-R, a call from GameRenderer now actually restores icons. Also called for WebGPU device loss and after contextChange WebGL restoration. Checks for WebGL context.isLost so a calls from Alt-R etc won't meddle while GL context is lost.
* **Orphaned Object Leaks:** In PixiJS v8, `Container.destroy()` does *not* recursively destroy its children. This PR explicitly adds `.destroy({ children: true })` inside icon deletion states. This stops thousands of `PIXI.Sprite` and `PIXI.BitmapText` child nodes from leaking and choking Pixi when it attempts a WebGL restore.
* **Texture Lifecycle:** Invalidate caching logic in `SpriteFactory` now correctly executes `.destroy(true)` on `PIXI.Texture` objects. Previously, they were only deleted from the textureCache Map, retaining a phantom grip on GPU memory buffers.
* **Don't remove PIXI.Texture.EMPTY from textureCache: `createTexture()` in `SpriteFactory` stores `PIXI.Texture.EMPTY` (a singleton) in `textureCache` when a structure type has no known shape. When not preventing removal of the EMPTY texture, `clearCache()` would call `texture.destroy(true)` on PixiJS's shared global empty texture, breaking all sprites in the renderer that fall back to it. 

**2. Small Memory/Perf Optimizations**
* **The Shared 2D Canvas Optimization:** To prevent allocating endless tiny `<canvas>` elements every time a structure color is loaded, `SpriteFactory` now utilizes a cleanly shared `colorCanvas` singleton. To keep this safe from hardware acceleration crashes (where the 2D context dies alongside WebGL), it accurately nullifies itself in `clearCache()` and lazily instantiates on the next call (`getImageColored()`).
* **Bypassing Inefficient Textures Cache:** Now passing the `skipCache: true` argument implicitly to dynamic UI elements via `PIXI.Texture.from(structureCanvas, true)`.
* **Zero-Allocation Filters (No more GC Stutters):** `renderGhost()` previously spawned numerous `new OutlineFilter(...)` WebGL shaders when hovering over invalid tiles, compounding to many leaked Shader Programs. We hoisted these filters to static class properties initialized once, and went a step further: hoisted the wrapping Array structures too (`filterRedArray`, `filterGreenArray`). This eliminates many pointless micro-allocations and GC sweeps entirely.

**BEFORE, for webGL:**
https://youtu.be/durJxNFNePs

**AFTER, for WebGL:**
https://youtu.be/VnYEFMx4gfM

**AFTER, for Canvas:**
https://youtu.be/zT720oKxcaI

**AFTER, for WebGPU:**
https://youtu.be/J09Wee2qTs8

The performance optimizations weren't well measurable in my tests but there's no downgrade at least. WebGPU should bee better than WebGL when we would force it but again, currently PixiJS prefers WebGL hardcoded so only if we disallow WebGL will it use WebGPU if it is available, otherwise fallback gracefully to Canvas still.

Canvas skips parts gracefully, as long as the non-breaking issue exists in PixiJS (as explained above):
AFTER Canvas in Firefox skips non-supported gracefully

## Please complete the following:

- [x] I have added screenshots for all UI updates
- [x] I process any text displayed to the user through translateText() and I've added it to the en.json file
- [x] I have added relevant tests to the test directory
- [x] I confirm I have thoroughly tested these changes and take full responsibility for any bugs introduced

## Please put your Discord username so you can be contacted if a bug or regression is found:

tryout33

### CODE REVIEW

File: src/client/graphics/layers/StructureIconsLayer.ts [hunk 1]
```diff
@@ -84,7 +85,7 @@ export class StructureIconsLayer implements Layer {
   private rootStage: PIXI.Container = new PIXI.Container();
   private dotsStage: PIXI.Container;
   private readonly theme: Theme;
-  private renderer: PIXI.Renderer | null = null;
+  private renderer: PIXI.WebGLRenderer | null = null;
```
Comment (scamiv) [inline src/client/graphics/layers/StructureIconsLayer.ts]: This moves from legacy autodetect to fixed renderer? Should probably use autoDetectRenderer ?
https://pixijs.download/release/docs/rendering.html
The pixi webgpu renderer actually seems nice, we should playtest it.

Comment (VariableVince) [reply src/client/graphics/layers/StructureIconsLayer.ts]: Implemented it, thanks for the reminder. It now supports WebGPU and Canvas too, including restore on context loss and when Alt-R is used for both those renderers too.

**Review by evanpelle — APPROVED** [review]
