### PR TITLE
A timer and icon flashing for betryal debuff

### LINKED ISSUE #2096: Disconnected ("Zzzz") during gameplay, connection ok, still see base being invaded but cannot react
**Describe the bug**
https://openfront.io/#join=JWKyurwc
By nickname "gus", at top of the map, after renew alliance with neighbor (just for timestamp reference), I became "Zzzz", but still see the game going and I believe green invading my base at the time I got that kind of disconnection.
I could not react. Clicked lots but game didnt respond to me, but I still see things happening, so, not local WiFi issue.
Instinctively hit F5 to try to refresh the game, but I screwed things up because I could only start watching the replay of the game then and could not continue playing from where it was.

**To Reproduce**
I am not sure, but maybe someone discovered some way to DDoS a player to make it going unresponsive for the game ? There are lots of pretty clever minds out there with lots of free time.

**Expected behavior**
Expected to end the "Zzzz" status and reconnect to the game, but didnt happen. I could see game going on but cannot react to it.
If I got disconnected, I believe I would not be able to see the game going, but I didnt went too far because I accidentally hit F5 under the pressure of losing my base.

**Screenshots**
I got only the replay link. My base went "Zzzz" on certain point even with my wifi going perfectly fine. The same time someone invaded my base. That timing was kind of suspicious.
https://openfront.io/#join=JWKyurwc

**Desktop (please complete the following information):**

- OS: Win 10
- Browser Brave
- Version [v 1.82.172]

**Additional context**

### PR DESCRIPTION
**Pull request by RjManhas**
Resolves #2096 

## Description:

(TO CLEARIFY THEIRS NO GRACE PERIOD ADDED, AS THAT ISSUE THAT WOULD OF NEEDED IT WAS FIXED BEFORE ON ITS OWN)

Shows the amount left in the UI for the player who trigged it
image

also the betryal icon, after 15 seconds starts a slow flash, then after 10 seconds it speeds up, and then at 5 seconds it quickly flashs.

this was a nice way to show the time left without adding any new ui componets.

video link 36 seconds (https://streamable.com/cwzxch)

## Please complete the following:

- [x] I have added screenshots for all UI updates
- [x] I process any text displayed to the user through translateText() and I've added it to the en.json file
- [x] I have added relevant tests to the test directory
- [x] I confirm I have thoroughly tested these changes and take full responsibility for any bugs introduced

## Please put your Discord username so you can be contacted if a bug or regression is found:

notifxy (1379678982676676639)

### CODE REVIEW

**Comment by RjManhas** [comment]
@evanpelle @VariableVince please review

File: src/client/graphics/layers/NameLayer.ts [hunk 1]
```diff
@@ -118,6 +118,20 @@ export class NameLayer implements Layer {
...
+      @keyframes traitorFlash {
+        0%, 100% {
+          opacity: 1;
+        }
+        50% {
+          opacity: 0.3;
+        }
+      }
+    `;
+    document.head.appendChild(style);
```
Comment (evanpelle) [inline src/client/graphics/layers/NameLayer.ts]: can we do this without appending css on the main document?

File: src/client/graphics/layers/NameLayer.ts [hunk 2]
```diff
@@ -410,16 +424,37 @@ export class NameLayer implements Layer {
...
+          this.traitorIconImage.src,
+          iconSize,
+          "traitor",
         );
+        iconsDiv.appendChild(existingTraitor);
+      }
+
+      // Apply flashing animation - staged speed increases at 15s, 10s, and 5s
+      if (existingTraitor instanceof HTMLImageElement) {
+        if (remainingSeconds <= 15) {
```
Comment (evanpelle) [inline src/client/graphics/layers/NameLayer.ts:445]: what do you think about a smooth transition? at the half way point start flashing slowing and then gradually increase the frequency

Comment (RjManhas) [reply src/client/graphics/layers/NameLayer.ts:445]: oooh thats a great idea ill work on that rn and btw @evanpelle sorry for doing so much at once, i know it takes lots of work from yall, i just love this game and want to help out lol

File: src/client/graphics/layers/NameLayer.ts (hunk 1 above)
Comment (RjManhas) [reply src/client/graphics/layers/NameLayer.ts]: ill look into it

File: src/client/graphics/layers/NameLayer.ts (hunk 2 above)
Comment (RjManhas) [reply src/client/graphics/layers/NameLayer.ts:445]: changed to a cubic ease out

File: src/client/graphics/layers/NameLayer.ts (hunk 1 above)
Comment (RjManhas) [reply src/client/graphics/layers/NameLayer.ts]: from my looking, unless theirs something i miss, not to do it without manually hidding and we enabling the icon which would probs be not good in terms of performance, i have changed it from apending to the head, to the container, to help localize it.

**Comment by RjManhas** [comment]
@evanpelle @VariableVince fixed changes

**Review by evanpelle — APPROVED** [review]
Thanks!
