### PR TITLE
Fix cache pathfinding

### LINKED ISSUE #843: Pathfinder cache causes boats to loop in circles
**Describe the bug**
If a boat partially caches a path, the next boat that follows that partial cache will get a desync between its pathfinder and its location, causing it to write a loop in to the path cache.

**To Reproduce**

1. Play the game
2. See boats looping

**Expected behavior**
Boats should write the full path to the cache when they perform pathfinding.

### PR DESCRIPTION
**Pull request by jrouillard**
## Description:
Add full path to caches
Fix A* to always start and end at given start and end
Remove pathfinder from tradeshipexecution

Should fix tradeship looping and getting stuck at ports
Fix #843

Dont know what to add so that description check is happy

[More lines to lines to make it happy]

## Please complete the following:

- [x] I have added screenshots for all UI updates
- [x] I confirm I have thoroughly tested these changes and take full responsibility for any bugs introduced
- [x] I understand that submitting code with bugs that could have been caught through manual testing blocks releases and new features for all contributors

## Please put your Discord username so you can be contacted if a bug or regression is found:

Vivacious Box

### CODE REVIEW

File: src/core/execution/TradeShipExecution.ts [hunk 1]
```diff
@@ -103,47 +103,69 @@ export class TradeShipExecution implements Execution {
...
-      this.tilesTraveled++;
+      this.moveTradeShip(cachedNextTile);
       return;
     }
 
-    const result = this.pathFinder.nextTile(
-      this.tradeShip.tile(),
-      this._dstPort.tile(),
-    );
+    const result = this.computeNewPath();
```
Comment (scottanderson) [inline src/core/execution/TradeShipExecution.ts]: I think you should inline this function, and remove the path field from this class.

File: src/core/execution/TradeShipExecution.ts [hunk 2]
```diff
@@ -103,47 +103,69 @@
...
+        consolex.warn("trade ship cannot find route");
         if (this.tradeShip.isActive()) {
           this.tradeShip.delete(false);
         }
         this.active = false;
         break;
+      default:
+        throw new Error("unexpected path finding compute result");
+    }
+  }
```
[the remark this answers is not in the document]
Comment (jrouillard) [reply src/core/execution/TradeShipExecution.ts]: A* doesnt return NextTile

File: src/core/game/UnitImpl.ts [hunk 3]
```diff
@@ -66,8 +66,18 @@ export class UnitImpl implements Unit {
     return this._targetTile;
   }
 
-  cachePut(from: TileRef, to: TileRef): void {
-    this._pathCache.set(from, to);
+  cachePut(path: TileRef[]): void {
```
Comment (scottanderson) [inline src/core/game/UnitImpl.ts]: I don't think this logic should be in UnitImpl. This behavior can be moved up to the caller.

File: src/core/pathfinding/MiniAStar.ts [hunk 4]
```diff
@@ -41,14 +41,46 @@ export class MiniAStar implements AStar {
...
 
   reconstructPath(): TileRef[] {
-    const upscaled = upscalePath(
+    let upscaled = upscalePath(
       this.aStar
         .reconstructPath()
         .map((tr) => new Cell(this.miniMap.x(tr), this.miniMap.y(tr))),
     );
-    upscaled.push(new Cell(this.gameMap.x(this.dst), this.gameMap.y(this.dst)));
+    upscaled = this.fixExtremes(upscaled);
```
Comment (scottanderson) [inline src/core/pathfinding/MiniAStar.ts]:
```ts
    const upscaled = fixExtremes(upscalePath(
      this.aStar
        .reconstructPath()
        .map((tr) => new Cell(this.miniMap.x(tr), this.miniMap.y(tr))),
    ));
```

File: src/core/pathfinding/MiniAStar.ts [hunk 5]
```diff
@@ -41,14 +41,46 @@ export class MiniAStar implements AStar {
...
     return upscaled.map((c) => this.gameMap.ref(c.x, c.y));
   }
+
```
Comment (scottanderson) [inline src/core/pathfinding/MiniAStar.ts]:
```suggestion
}

```

File: src/core/pathfinding/MiniAStar.ts [hunk 6]
```diff
@@ -41,14 +41,46 @@ export class MiniAStar implements AStar {
...
+    if (dstIndex === -1) {
+      // didnt find the dst tile in the path
+      upscaled.push(cellDst);
+    } else if (dstIndex !== upscaled.length - 1) {
+      // found dst tile but not at the end
+      // remove all tiles after the dst tile
+      upscaled = upscaled.slice(0, dstIndex + 1);
+    }
+    return upscaled;
+  }
```
Comment (scottanderson) [inline src/core/pathfinding/MiniAStar.ts:76]:
```suggestion
```

**Review by scottanderson — CHANGES_REQUESTED** [review]

File: src/core/execution/TradeShipExecution.ts [hunk 7]
```diff
@@ -103,47 +103,69 @@
...
+      case PathFindResultType.Completed:
+        this._dstPort.cachePut(this.path);
+        if (!this.wasCaptured) {
+          this.srcPort.cachePut(this.path.slice().reverse());
         }
-        this.tradeShip.move(result.tile);
-        this.tilesTraveled++;
+        this.moveTradeShip(this.path.shift());
         break;
       case PathFindResultType.PathNotFound:
```
[the remark this answers is not in the document]
Comment (jrouillard) [reply src/core/execution/TradeShipExecution.ts]: The path length is already checked in the compute function, it cannot be completed and empty

**Review by scottanderson — APPROVED** [review]

**Review by evanpelle — APPROVED** [review]
