### PR TITLE
fix: show Spectate instead of Keep Playing on win modal when dead Closes #3058

### LINKED ISSUE #3058: Bug: "Keep Playing" instead of "Spectate" on second win modal in Teams
When you're killed in a Teams game, the 'win modal' will correctly show a "Spectate" button if you want to keep watching.

But then if your Team wins while you kept watching, the team win modal will have that button labeled as "Keep Playing". It should still be "Spectate" because your player was already dead.

### PR DESCRIPTION
**Pull request by GhadiSaab**
## Description:                                                        
  This PR resolves issue #3058 where the "win modal" incorrectly         
  displayed a **"Keep Playing"** button instead of **"Spectate"** when a 
  player's team won but the player themselves was already dead.          
                                                                         
  ### The Problem                                                        
  In WinModal.ts, the button text logic only checked `this.isWin`        
  (whether the team won) but didn't verify if the player was still alive.
   This caused dead players on winning teams to see "Keep Playing"       
  instead of "Spectate".                                                 
                                                                         
  ### The Solution                                                       
  Updated the button rendering logic in                                  
  `src/client/graphics/layers/WinModal.ts:82` to check both the win      
  condition AND the player's alive status:                               
                                                                         
  ```typescript                                                          
  // Before                                                              
  ${this.isWin                                                           
    ? translateText("win_modal.keep")                                    
    : translateText("win_modal.spectate")}                               
                                                                         
  // After                                                               
  ${this.isWin && this.game.myPlayer()?.isAlive()                        
    ? translateText("win_modal.keep")                                    
    : translateText("win_modal.spectate")}
  ```                               
                                                                         
  This approach maintains clean separation of concerns:                  
  - this.isWin continues to represent whether the player's team won      
  (true/false)                                                           
  - The button text logic now checks both team victory and player alive  
  status                                                                 
  - This ensures the correct button appears based on the player's actual 
  state                                                                  
                                                                         
  Behavior After Fix                                                     
                                                                         
  - Alive players on the winning team → "Keep Playing"                   
  - Dead players on the winning team → "Spectate"                        
  - Any player on the losing team → "Spectate"                           
                                                                         
  Testing Performed                                                      
                                                                         
  1. Code Audit: Verified myPlayer().isAlive() correctly reflects the    
  eliminated state in Teams mode.                                        
  2. Build Verification: Ran npm run build and npm run build-prod to     
  ensure no regressions in the UI layer.                                 
  3. Type Safety: Ran tsc --noEmit to confirm the fix is fully compliant 
  with the project's TypeScript strictness.                              
                                                                         
  ---                                                                    
  Closes #3058                                                           
                                                                         
## Please complete the following:                                         
                                                                         
- [x] I have added screenshots for all UI updates
- [x] I process any text displayed to the user through translateText() and I've added it to the en.json file
- [x] I have added relevant tests to the test directory
- [x] I confirm I have thoroughly tested these changes and take full responsibility for any bugs introduced                       
                                                                         
## Please put your Discord username so you can be contacted if a bug or regression is found:                                                   
                                                                         
  ghadi8097

### CODE REVIEW

File: src/client/graphics/layers/WinModal.ts [hunk 1]
```diff
@@ -294,7 +294,7 @@ export class WinModal extends LitElement implements Layer {
         this.eventBus.emit(new SendWinnerEvent(wu.winner, wu.allPlayersStats));
         if (wu.winner[1] === this.game.myPlayer()?.team()) {
           this._title = translateText("win_modal.your_team");
-          this.isWin = true;
+          this.isWin = this.game.myPlayer()?.isAlive() ?? false;
```
Comment (evanpelle) [inline src/client/graphics/layers/WinModal.ts]: don't we still want to keep this as a win?

Comment (VariableVince) [reply src/client/graphics/layers/WinModal.ts]: Agree. Maybe just check if player is alive on line 82 and let isWin be true here?

Comment (GhadiSaab) [reply src/client/graphics/layers/WinModal.ts]: > Agree. Maybe just check if player is alive on line 82 and let isWin be true here?

you are right, my bad. I made the changes

File: src/client/graphics/layers/WinModal.ts [hunk 2]
```diff
@@ -79,7 +79,7 @@ export class WinModal extends LitElement implements Layer {
             @click=${this.hide}
             class="flex-1 px-3 py-3 text-base cursor-pointer bg-blue-500/60 text-white border-0 rounded-sm transition-all duration-200 hover:bg-blue-500/80 hover:-translate-y-px active:translate-y-px"
           >
-            ${this.isWin
+            ${this.isWin && this.game.myPlayer()?.isAlive()
               ? translateText("win_modal.keep")
               : translateText("win_modal.spectate")}
```
Comment (evanpelle) [inline src/client/graphics/layers/WinModal.ts]: just thinking, it actually shouldn't matter if we won or not right? if we are alive => keep playing, if we died => spectate

**Review by evanpelle — DISMISSED** [review]

**Comment by ryanbarlow97** [comment]
@GhadiSaab also please update your description with the template/checkboxes

File: src/client/graphics/layers/WinModal.ts (hunk 2 above)
Comment (GhadiSaab) [reply src/client/graphics/layers/WinModal.ts]: hm, yes i think you are right. its unnecessary but it was already here and i dont really know if something depends on this specific check. adding the && was to play it safe. do you want me to change it ?

**Comment by GhadiSaab** [comment]
> @GhadiSaab also please update your description with the template/checkboxes

i have made the changes

**Comment by VariableVince** [comment]
> > @GhadiSaab also please update your description with the template/checkboxes
> 
> i have made the changes

Thanks. If you want a re-review you can click the button to the right of evanpelle's name under Reviewers. I'll also let him know in the discord.

File: src/client/graphics/layers/WinModal.ts (hunk 2 above)
Comment (evanpelle) [reply src/client/graphics/layers/WinModal.ts]: yeah i think it makes sense to change it

Comment (GhadiSaab) [reply src/client/graphics/layers/WinModal.ts]: i have made the changes
