### PR TITLE
Team leaderboard: own team bold + fix headers allignment

### LINKED ISSUE #2185: Highlight the own Team in Bold in the Leaderboard in Team Games
In the normal single player leaderboard, the own Name is highlightened in bold letters.
Similarly in the team leaderboard it would be great to highlight the own Team in bold letters.

### PR DESCRIPTION
**Pull request by VariableVince**
## Description:

Closes #2185. Made own team name bold in Team Stats. In Show Unit and Show Control. This follows https://github.com/openfrontio/OpenFrontIO/pull/2221 which made team mate names bold in the Leaderboard.

Also fixed column names allignment. They sat in different vertical positions before.

**BEFORE**

image

image

**AFTER**

image

image

## Please complete the following:

- [x] I have added screenshots for all UI updates
- [x] I process any text displayed to the user through translateText() and I've added it to the en.json file
- [x] I have added relevant tests to the test directory
- [x] I confirm I have thoroughly tested these changes and take full responsibility for any bugs introduced

## Please put your Discord username so you can be contacted if a bug or regression is found:

tryout33

### CODE REVIEW

File: src/client/graphics/layers/TeamStats.ts [hunk 1]
```diff
@@ -54,6 +56,11 @@ export class TeamStats extends LitElement implements Layer {
     const players = this.game.playerViews();
     const grouped: Record<Team, PlayerView[]> = {};
 
+    if (this._myTeam === null) {
+      const myPlayer = this.game.myPlayer();
```
Comment (jrouillard) [inline src/client/graphics/layers/TeamStats.ts:60]: I don't think we need to check the team for each ticks, maybe move it in the init method

Comment (VariableVince) [reply src/client/graphics/layers/TeamStats.ts:60]: In the init is too early sadly, team is still null at that point.

I did put it in updateTeamStats(), which is called every 10 ticks from tick(). And it has a null check so the fetch and assignment happens only once. But the null check every 10 ticks seems unavoidable
