### PR TITLE
Fix Ctrl+Click for Macs, and alphabetize gitignore

### LINKED ISSUE #2719: Ctrl+Click on Mac opens radial menu, but *also* performs an attack
**Describe the bug**
On Macs, any time you ctrl+click to open the radial menu, it tries to attack whoever your mouse happens to be on.

This doesn't happen on Windows/Linux.

**To Reproduce**
1. Hover over any non-ally with a land border or boatable-border
2. Ctrl+Click on a mac to open radial menu
3. Oops you now perma-aggro'd them if they're a Nation.

**Expected behavior**
If Ctrl button is held down when a click happens on Mac:
1. The radial menu should open
2. Any logic to attack someone should not happen, because Ctrl was being held down.

**Screenshots**

**Desktop (please complete the following information):**

- **OS:** Mac - Sonoma 14.1
- **Browser:** Brave
- **Version**: Every version (`v0.28.2` in this case)

**Smartphone (please complete the following information):**
N/A

**Additional context**
On Windows/Linux:
* Ctrl+click → Opens build menu (via ShowBuildMenuEvent)
* Right-click → Opens radial menu (via contextmenu event)

On Mac:
* Cmd+click → Opens build menu
* Right-click → Opens radial menu
* Ctrl+click (trackpad) → Opens radial menu (browser treats as right-click) + attacks (bug)

---
Notes to self...probably around here:

`InputHandler.ts:489-496:`

```js
if (this.isModifierKeyPressed(event)) {
  this.eventBus.emit(new ShowBuildMenuEvent(event.clientX, event.clientY));
  return;
}
if (this.isAltKeyPressed(event)) {
  this.eventBus.emit(new ShowEmojiMenuEvent(event.clientX, event.clientY));
  return;
}
```

And line 203:
```js
modifierKey: isMac ? "MetaLeft" : "ControlLeft",
```

### PR DESCRIPTION
**Pull request by clounie**
Resolves #2719 
- [X] Ran `npm run format`
- [X] Ran `npm run lint:fix`
- [X] Ran `npm test`
- [X] Manually tested fixes

### What problem(s) was I solving?

On Mac, `Ctrl+Click` is commonly used as a substitute for right-click to open context menus. However, in OpenFront, `Ctrl+Click` was triggering both the context menu, AND causing an attack. 

This effectively prevented Mac users from being able to ally with bots/nations, as trying to ally would cause you to attack them.

### What changes did I make?
- `Ctrl+Click` on Mac no longer triggers an attack, allowing players to properly interact with the alliance system

### How I implemented it

1. Added an `isMac()` method to `InputHandler` which encapsulates the "is mac" logic, and lets it be mocked during tests
2. In the `onPointerUp` handler, added a check: if on Mac and `ControlLeft` is held, emit a `ContextMenuEvent`, and then return (instead of continuing to also create a `MouseUpEvent`)
3. Extracted magic numbers for mouse button checks into descriptive helper methods (`isMiddleMouseButton`, `isNonLeftMouseButton`) for improved code clarity
4. Added clarifying comments throughout the pointer event handlers

Last, alphabetized the `.gitignore` file and organized it into "Folders" and "Files" sections to make it easier to read.

#### Manual Testing
- [X] On a Mac, hold `Ctrl` and left-click on another nation - verify the context menu opens (not an attack)
- [X] On a Mac, right-click should still open the context menu as expected
- [X] On Windows/Linux, `Ctrl+Click` continue to work as before (modifier key for build menu if configured)
- [X] Regular left-click still triggers attacks/interactions as expected

#### Automated Testing
- [x] New unit test added: `Mac Ctrl+Click Context Menu` - verifies that `Ctrl+Click` on Mac emits `ContextMenuEvent` instead of `MouseUpEvent`

### Description for the changelog

Fixed `Ctrl+Click` on Mac to properly open the context menu instead of triggering an attack, restoring the ability for Mac users to form alliances with other nations.

## Please complete the following:

- [X] I have added screenshots for all UI updates
- [X] I process any text displayed to the user through translateText() and I've added it to the en.json file
- [X] I have added relevant tests to the test directory
- [X] I confirm I have thoroughly tested these changes and take full responsibility for any bugs introduced

## Please put your Discord username so you can be contacted if a bug or regression is found:
Terekhov

### CODE REVIEW

File: src/client/InputHandler.ts [hunk 1]
```diff
@@ -490,15 +498,27 @@ export class InputHandler {
...
 
+    // If Ctrl is held down (for example, on a Mac which doesn't have a right-click)
+    // then Ctrl+Click is used to open context menu.
+    //
+    // Without this conditional, Ctrl+click causes the player to attack someone
+    // if they are not allied, effectively removing ability to ally with bots/nations.
+    if (this.isMac() && this.activeKeys.has("ControlLeft")) {
+      this.eventBus.emit(new ContextMenuEvent(event.clientX, event.clientY));
+      return;
+    }
```
[the remark this answers is not in the document]
Comment (clounie) [reply src/client/InputHandler.ts:515]: Considered this, but decided not to include since ControlRight is so far away from the normally used modifiers.

Not heartburn over adding it, just didn't seem worth.

**Comment by iiamlewis** [comment]
@clounie can you resolve the branch conflicts and I'll look and see what I can do about getting this reviewed!

File: src/client/InputHandler.ts [hunk 2]
```diff
@@ -475,12 +481,14 @@ export class InputHandler {
...
-    if (event.button === 1) {
+    // Prevent default behavior for middle mouse button, but don't process further
+    if (this.isMiddleMouseButton(event.button)) {
       event.preventDefault();
       return;
     }
 
-    if (event.button > 0) {
+    // Ignore right mouse button and other non-left buttons
+    if (this.isNonLeftMouseButton(event.button)) {
```
Comment (DevelopingTom) [inline src/client/InputHandler.ts]: Nitpick: looks convoluted. Could you reverse the logic? "!isLeftMouseButton()"

**Review by DevelopingTom — COMMENTED** [review]
Looks good to me but can't try it without a Mac.

File: src/client/InputHandler.ts (hunk 2 above)
Comment (clounie) [reply src/client/InputHandler.ts]: Fixed, good call thanks.

**Comment by clounie** [comment]
@iiamlewis should be good to go -
* Resolved conflicts
* Adopted vitest for my tests
* Re-ran format/lint/test, everything passed
* Re-tested in UI, `Ctrl+Click` and `Cmd+Click` both still work as expected after update
  * `Ctrl+Click` does not attack
  * `Cmd+Click` behavior unchanged

**Comment by ryanbarlow97** [comment]
@clounie this broke non mac pcs

**Comment by clounie** [comment]
> @clounie this broke non mac pcs

I'll have to debug. At first glance this seems to imply the `isMac` boolean must be broken in some way, as-is. Or that moving it to instance state broke it..

For future me - "Commit breaks map dragging ability."
