### PR TITLE
Fix middle-click SAM not upgrading other buildings when SAM is unaffo…

### LINKED ISSUE #3511: Bug - Middle-clicking a SAM should never upgrade non-SAM buildings
If you middle-click a SAM you own, and have at least 3.00M gold, that SAM gets upgraded. This is normal and expected. But if you middle-click a SAM and have 2.99M gold, and there is a nearby building, that building gets upgraded instead. And now you have 1.99M gold. This is really upsetting when a hydrogen bomb is coming in, and you are desperately trying to upgrade your SAMs before it reaches you. Middle-clicking a SAM should either upgrade it or take no action, not spend gold (which takes you further away from upgrading the SAM).

### PR DESCRIPTION
**Pull request by baculinivan-web**
Resolves #3511

## Description:
When middle-clicking a SAM launcher you own, the game calls findAndUpgradeNearestBuilding which queries all upgradeable structures near the clicked tile. If you can't afford the SAM upgrade, canUpgrade is false for the SAM (because canBuildUnitType returns false when gold < cost), so the SAM is excluded from the candidates list. If a nearby building (e.g. a Factory) can be upgraded, it gets picked as the "nearest" target and is upgraded instead — spending gold the player was saving for the SAM.

The fix: after finding the best upgrade candidate, check if there's an owned SAM within the same search radius as the clicked tile. If there is, but the best candidate is not a SAM (meaning the SAM couldn't be afforded), do nothing instead of upgrading the other building. This ensures middle-clicking a SAM either upgrades it or takes no action.

##Please complete the following:

- [x] I have added screenshots for all UI updates
- [x] I process any text displayed to the user through translateText() and I've added it to the en.json file
- [x] I have added relevant tests to the test directory
- [x] I confirm I have thoroughly tested these changes and take full responsibility for any bugs introduced

## Please put your Discord username so you can be contacted if a bug or regression is found:

fghjk_60845

### CODE REVIEW

**Comment by ryanbarlow97** [comment]
I'm glad someone else was annoyed by this

**Comment by baculinivan-web** [comment]
> I'm glad someone else was annoyed by this

I found the issue and then understood that it happens and i was post-annoyed

File: src/client/ClientGameRunner.ts [hunk 1]
```diff
@@ -654,17 +654,36 @@ export class ClientGameRunner {
...
+      }
+
+      if (bestUpgrade.unitType !== UnitType.SAMLauncher) {
+        const samBlockedByGold = actions.buildableUnits.some(
+          (bu) => bu.type === UnitType.SAMLauncher && bu.canUpgrade === false,
+        );
+        if (samBlockedByGold) {
+          // A SAM near clickedTile exists but can't be upgraded yet — do nothing.
+          return;
         }
```
[the remark this answers is not in the document]
Comment (baculinivan-web) [reply src/client/ClientGameRunner.ts]: @CodeRabbitAI resolve

**Comment by baculinivan-web** [comment]
@coderabbitai resolve

**Comment by iiamlewis** [comment]
Added to PR review

File: src/client/ClientGameRunner.ts [hunk 2]
```diff
@@ -654,17 +654,58 @@ export class ClientGameRunner {
...
+      // entry with canUpgrade===false (SAM exists near clickedTile but can't be
+      // afforded right now), do nothing — the player intended to upgrade that
+      // SAM and we must not spend their gold on a different building.
+      const bestUpgrade = findClosestBy(upgradeUnits, (u) => u.distance);
+      if (!bestUpgrade) {
+        return;
+      }
+
+      if (bestUpgrade.unitType !== UnitType.SAMLauncher) {
+        // Block the upgrade only if the closest own SAM to clickedTile is
```
Comment (evanpelle) [inline src/client/ClientGameRunner.ts]: Should we do this for all units instead of just the SAM?

Comment (baculinivan-web) [reply src/client/ClientGameRunner.ts]: No, Sam has the higher price, Thats why we need this filtering

Comment (evanpelle) [reply src/client/ClientGameRunner.ts]: Is it possible thhat a city could cost 1M and a nearby factory 500k? less likely than the SAM

Comment (baculinivan-web) [reply src/client/ClientGameRunner.ts]: Right. Didn't think about that. Would fix

**Comment by baculinivan-web** [comment]
@coderabbitai review

File: src/client/ClientGameRunner.ts (hunk 2 above)
Comment (baculinivan-web) [reply src/client/ClientGameRunner.ts]: Done. Re Review, pplease

**Review by evanpelle — APPROVED** [review]
