### PR TITLE
fix: allies cannot annex your clusters

### LINKED ISSUE #1685: Allied players can capture my area
**Describe the bug**

Game version: v0.24.11
Host: https://openfront.io/
Game ID: JpHDabXg

The area outlined in red was owned by the bot "Canada" before it was conquered by me. The allied player from below attacked the remains of the land of this bot. Resulting from that, this "outer district" was claimed by them. I consider this a bug because this should not happen for allied players.

**To Reproduce**
Steps to reproduce the behaviour:

1. Join an FFA map
2. Claim an "outer district"-looking area
3. Get an ally to attack the common enemy.
4. Lose your area.

**Expected behavior**
Automatic area claiming should not occur if the other party is allied

**Screenshots**

Image

**Desktop (please complete the following information):**

- OS: does
- Browser: not
- Version: matter

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by nottirb**
## Description:

Fixes #1685
Continuation from #1924, which was auto-closed after the upstream repo force-pushed main and I synced my fork.

This change ensures that allies are excluded from the `getMode()` call made by `getCapturingPlayer()` inside `removeCluster()`.

 - Previously, friendly neighbors were treated as candidates for capturing, leading to incorrect annexations in certain edge cases.
 - Added a small efficiency improvement by filtering out non-player and friendly neighbors up front to reduce total computations down-the-line.
 - Important: we can’t simply check if the `getMode(neighborsIDs)` result is a friendly. Doing so would cause the territory to go to nobody until the user is attacked. I believe the expected behavior is the largest neighboring enemy should take it automatically.

Here's an example of the new behavior in an extreme edge case:
Screenshot 2025-08-24 at 4 56 46 PM

## Please complete the following:

- [X] I have added screenshots for all UI updates
- [X] I process any text displayed to the user through translateText() and I've added it to the en.json file
- [X] I have added relevant tests to the test directory
- [X] I confirm I have thoroughly tested these changes and take full responsibility for any bugs introduced

## Please put your Discord username so you can be contacted if a bug or regression is found:

nottirb

### CODE REVIEW

File: src/core/execution/PlayerExecution.ts [hunk 1]
```diff
@@ -238,11 +255,8 @@ export class PlayerExecution implements Execution {
       return largestNeighborAttack;
     }
 
-    // fall back to getting mode if no attacks
+    // Fall back to getting mode if no attacks
     const mode = getMode(neighborsIDs);
```
Comment (evanpelle) [inline src/core/execution/PlayerExecution.ts]: I think this was an existing bug, but it looks like we're trying to get the mode of a set?

File: src/core/execution/PlayerExecution.ts [hunk 2]
```diff
@@ -209,22 +209,39 @@ export class PlayerExecution implements Execution {
...
+          candidatesIDs.add(this.mg.ownerID(neighbor));
         }
       }
     }
 
-    let largestNeighborAttack: Player | null = null;
-    let largestTroopCount: number = 0;
-    for (const id of neighborsIDs) {
+    // Filter out friendly and non-player candidates
+    const neighborsIDs = new Set<number>();
```
Comment (evanpelle) [inline src/core/execution/PlayerExecution.ts]: do we need this set? looks like a duplicate of neighbors.

Comment (evanpelle) [reply src/core/execution/PlayerExecution.ts]: I think maybe if there are no active attacks, we just don't do anything. so we can actually remove the neighborsIDs set and remove the getMode().

Comment (nottirb) [reply src/core/execution/PlayerExecution.ts]: The set is necessary insofar as the input to getMode has to be ID's instead of player objects.

Removing getMode definitely makes this set worthless though.

File: src/core/execution/PlayerExecution.ts (hunk 1 above)
Comment (nottirb) [reply src/core/execution/PlayerExecution.ts]: Yep seems like it.

We could replace getMode with something that calculates the largest neighbor by tile count or just scrap it entirely.

Both seem relatively easy to do.
