### PR TITLE
Fix flag preview not updating after selecting a new flag

### LINKED ISSUE #1803: Flag preview not updating
**Describe the bug**
The flag preview button is not updating after selecting a new flag.

**To Reproduce**
step 1: open flag modal
step 2: pick a new flag
step 3: close flag modal
result: flag preview has not been updated. Refreshing the page updates the flag.

### PR DESCRIPTION
**Pull request by Aotumuri**
## Description:
Fixed to redraw when triggered by a custom event (flag-change).
Fixes https://github.com/openfrontio/OpenFrontIO/issues/1803

## Please complete the following:

- [x] I have added screenshots for all UI updates
- [x] I process any text displayed to the user through translateText() and I've added it to the en.json file
- [x] I have added relevant tests to the test directory
- [x] I confirm I have thoroughly tested these changes and take full responsibility for any bugs introduced

## Please put your Discord username so you can be contacted if a bug or regression is found:
aotumuri

### CODE REVIEW

**Comment by scottanderson** [comment]
@Aotumuri please make sure to follow https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue when you are working on existing issue.

**Review by scottanderson — CHANGES_REQUESTED** [review]
The required description field is incomplete. Our commit message and PR description rules are not optional. Filling the field with placeholder or meaningless text just to meet the minimum character count is not acceptable. This undermines the purpose of the rule and erodes trust within the team. Please take the time to write a meaningful description that accurately reflects the changes in this PR so we can work effectively together.

**Review by scottanderson — APPROVED** [review]

**Review by scottanderson — CHANGES_REQUESTED** [review]
description

File: src/client/FlagInput.ts [hunk 1]
```diff
@@ -41,10 +41,24 @@ export class FlagInput extends LitElement {
     );
   }
 
+  private updateFlag = (ev: Event) => {
+    const e = ev as CustomEvent<{ flag: string }>;
+    if (!e?.detail || typeof e.detail.flag !== "string") return;
+    if (this.flag !== e.detail.flag) {
+      this.flag = e.detail.flag;
```
Comment (woodydrn) [inline src/client/FlagInput.ts:49]: We need to update localStorage "flag" as well right?

We can check for flag is valid too, by using `FlagSchema.safeParse(e.detail.flag).success`

**Comment by Aotumuri** [comment]
> description

sorry I fixed

File: src/client/FlagInput.ts (hunk 1 above)
Comment (Aotumuri) [reply src/client/FlagInput.ts:49]: The localStorage update should be handled on the event sender’s side, so I believe there shouldn’t be any issue.

Comment (Aotumuri) [reply src/client/FlagInput.ts:49]: I’ve modified it to use FlagSchema.
Could you please confirm if this is correct?

Comment (woodydrn) [reply src/client/FlagInput.ts:49]: Yes that is working perfectly

**Review by woodydrn — APPROVED** [review]

**Review by scottanderson — APPROVED** [review]
