### PR TITLE
fix: traitor bug when attacking immediately after initiating an alliance

### LINKED ISSUE #1866: Traitor debuff triggers if alliance is accepted while an attack click is in progress (race condition)
**Describe the bug**
Sometimes the 50% “Traitor” debuff is applied even though an alliance has just been accepted. This happens when one player is mid-attack and clicks at the exact moment the alliance request is accepted, causing the game to treat the attack as a betrayal.

**To Reproduce**

1- Player A and Player B are not allied.
2- Player A begins an attack on Player B (click to attack).
3 - While Player A is still in the “attack” input (Not sure if the player must be attacking to trigger this bug), an alliance request between A and B gets accepted (either direction).
4 - Player A sends attacks right after the alliance acceptance.

**Actual behavior**
Player A immediately gets the 50% Traitor debuff, even though the alliance was just accepted.

**Expected behavior**
The attack should be canceled, and no Traitor debuff should be applied.

**Screenshots**

**https://drive.google.com/file/d/1YuYET07blnP8N5qPud25eRWWyg0_HI-B/view?usp=sharing**

If accepted, please assign this issue to @AbdallahBahrawi (me). I’m happy to work on a fix.

### PR DESCRIPTION
**Pull request by abdallahbahrawi1**
## Description:

This PR fixes a critical race condition bug where players could unintentionally receive the traitor debuff when alliance requests were accepted mid-attack.

Critical Bug Fixes #1866

**Root Cause:** 
Players could bypass UI alliance checks ( isFriendly() ) by accepting alliances and immediately attacking after that, causing the server to treat the attack as betrayal
Solution: Added server-side alliance validation in AttackExecution.init()
This ensures attacks on allies are blocked at the server level.

- Once Bots and Nations decide to attack, they breaks the alliance. I added maybeConsiderBetrayal(), which currently always returns true. I’ll add proper logic for alliance-breaking soon on another PR; this didn’t exist in the code before.

## Please complete the following:

- [x] I have added screenshots for all UI updates
- [x] I process any text displayed to the user through translateText() and I've added it to the en.json file
- [x] I have added relevant tests to the test directory
- [x] I confirm I have thoroughly tested these changes and take full responsibility for any bugs introduced

## Please put your Discord username so you can be contacted if a bug or regression is found:

abodcraft1

### CODE REVIEW

File: src/core/execution/BotExecution.ts [hunk 1]
```diff
@@ -69,6 +69,18 @@ export class BotExecution implements Execution {
...
+        // Check and break alliance before attacking if needed
+        if (this.bot.isAlliedWith(toAttack)) {
+          const alliance = this.bot.allianceWith(toAttack);
+          if (alliance !== null) {
+            this.bot.breakAlliance(alliance);
+          }
+          // Don't attack friendly players
+          if (this.bot.isFriendly(toAttack)) {
+            return;
+          }
```
Comment (evanpelle) [inline src/core/execution/BotExecution.ts]: would this case every be true? since you can't ally teammates.

File: src/core/execution/BotExecution.ts [hunk 2]
```diff
@@ -69,6 +69,18 @@ export class BotExecution implements Execution {
     if (toAttack !== null) {
       const odds = this.bot.isFriendly(toAttack) ? 6 : 3;
       if (this.random.chance(odds)) {
+        // Check and break alliance before attacking if needed
+        if (this.bot.isAlliedWith(toAttack)) {
```
Comment (evanpelle) [inline src/core/execution/BotExecution.ts]: instead of checking isAlliedWith,  get the alliance and then check if it's null. just a bit cleaner imo

File: src/core/execution/FakeHumanExecution.ts [hunk 3]
```diff
@@ -162,6 +162,16 @@ export class FakeHumanExecution implements Execution {
...
   }
 
+  private maybeConsiderBetrayal(target: Player): boolean {
+    if (this.player === null) throw new Error("not initialized");
+    const alliance = this.player.allianceWith(target);
+    if (!alliance) return false;
+    // Break first; traitor state is handled elsewhere by game rules/tests.
+    this.player.breakAlliance(alliance);
+    // Proceed only when no longer friendly (e.g., not allied or same team).
+    return !this.player.isFriendly(target);
```
Comment (evanpelle) [inline src/core/execution/FakeHumanExecution.ts]: same here, i don't think this case is ever possible

File: src/core/execution/FakeHumanExecution.ts [hunk 4]
```diff
@@ -209,7 +219,15 @@ export class FakeHumanExecution implements Execution {
     const toAttack = this.random.chance(2)
       ? enemies[0]
       : this.random.randElement(enemies);
-    if (this.shouldAttack(toAttack)) {
+
+    // First consider betrayal, then normal attack logic
+    if (this.player.isAlliedWith(toAttack)) {
+      const canProceed = this.maybeConsiderBetrayal(toAttack);
+      if (canProceed && !this.player.isFriendly(toAttack)) {
```
Comment (evanpelle) [inline src/core/execution/FakeHumanExecution.ts]: same here, i don't think we need the isFriendly check
