### PR TITLE
Cancel nukes when accepting alliance via radial menu

### LINKED ISSUE #3154: Incoming nukes are not destroyed if alliance is accepted via radial menu
**Describe the bug**
The feature introduced in #2716 works only when the receiving player accepts the alliance request via EventsDisplay, not via Radial Menu.

**To Reproduce**

1. Throw a nuke to a player
2. Offer him the alliance
3. Receiving player accepts the alliance via radial menu
4. The nuke is not destroyed

**Expected behavior**
The nuke is destroyed mid-air and both users are notified via EventsDisplay.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by deshack**
Resolves #3154

## Description:

#2716 introduced nuke cancellation logic on alliance acceptance via `AllianceRequestReplyExecution`. The radial menu action, though, calls `AllianceRequestExecution` instead, which accepts the alliance if a request has already been made by the other player.

This PR moves the nuke cancellation logic to `GameImpl`, hooking into the `acceptAllianceRequest` method, therefore accounting for every alliance acceptance, regardless of the specific action that brought to that.

## Please complete the following:

- [x] I have added screenshots for all UI updates
- [x] I process any text displayed to the user through translateText() and I've added it to the en.json file
- [x] I have added relevant tests to the test directory
- [x] I confirm I have thoroughly tested these changes and take full responsibility for any bugs introduced

## Please put your Discord username so you can be contacted if a bug or regression is found:

deshack_82603

### CODE REVIEW

File: src/core/execution/alliance/AllianceRejectExecution.ts
Comment (evanpelle) [inline src/core/execution/alliance/AllianceRejectExecution.ts:1]: Would it be possible to just remove this execution? And then events display and radial menu can just send AllianceRequest? Then all alliance logic would be in a single file, and we can move cancelNukesBetweenAlliedPlayers there.

File: src/core/game/GameImpl.ts [hunk 1]
```diff
@@ -359,6 +362,53 @@ export class GameImpl implements Game {
     });
   }
 
+  private cancelNukesBetweenAlliedPlayers(p1: Player, p2: Player): void {
```
Comment (evanpelle) [inline src/core/game/GameImpl.ts]: GameImpl should ideally be just a container to hold game state and not have much complex logic.

File: src/core/execution/alliance/AllianceRejectExecution.ts
Comment (deshack) [reply src/core/execution/alliance/AllianceRejectExecution.ts:1]: I centralised acceptance logic in `AllianceRequestExecution` and created a new `AllianceRejectExecution` to handle rejections, because:
- semantics: you'll never look for the rejection path inside Alliance **Request** Execution
- SRP: adding a new parameter to `AllianceRequestExecution` to branch out its logic and handle rejections felt really wrong to me

File: src/core/game/GameImpl.ts (hunk 1 above)
Comment (deshack) [reply src/core/game/GameImpl.ts]: Moved to `AllianceRequestExecution`

File: src/core/execution/alliance/AllianceRejectExecution.ts [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+      console.warn(
+        `AllianceRejectExecution requester ${this.requestorID} not found`,
+      );
+      this.active = false;
+      return;
+    }
+    const requestor = mg.player(this.requestorID);
+
+    if (requestor.isFriendly(this.recipient)) {
+      console.warn("already allied");
```
Comment (evanpelle) [inline src/core/execution/alliance/AllianceRejectExecution.ts]: here and on line 28 can you log something like:

console.warn("[AllianceRejectExecution] Player ${this.requestorID} cannot reject alliance with ${this.recipient.id}, already allied"

File: src/core/game/GameImpl.ts [hunk 3]
```diff
@@ -332,12 +333,19 @@ export class GameImpl implements Game {
...
+
     // Automatically remove embargoes only if they were automatically created
     if (requestor.hasEmbargoAgainst(recipient))
       requestor.endTemporaryEmbargo(recipient);
     if (recipient.hasEmbargoAgainst(requestor))
       recipient.endTemporaryEmbargo(requestor);
 
+    // Cancel incoming nukes between players
+    cancelNukesBetweenAlliedPlayers(this, requestor, recipient);
+
```
Comment (evanpelle) [inline src/core/game/GameImpl.ts]: this also adds a lot of logic into GameImpl, gameimpl should ideally just store & update state. Can this be removed?

Same with line 337 & 338

Comment (deshack) [reply src/core/game/GameImpl.ts]: Moved all the logic into `AllianceImpl.onCreate()`. Should be consistent with what is commonly done in `PlayerImpl`.

We still need to call it from here, since we don't have the alliance instance before.

File: src/core/game/AllianceImpl.ts [hunk 4]
```diff
@@ -75,4 +82,68 @@ export class AllianceImpl implements MutableAlliance {
...
+    if (this.requestor_.hasEmbargoAgainst(this.recipient_))
+      this.requestor_.endTemporaryEmbargo(this.recipient_);
+    if (this.recipient_.hasEmbargoAgainst(this.requestor_))
+      this.recipient_.endTemporaryEmbargo(this.requestor_);
+
+    // Cancel incoming nukes between players
+    this.cancelNukesBetweenAlliedPlayers();
+  }
+
+  cancelNukesBetweenAlliedPlayers(): void {
```
Comment (evanpelle) [inline src/core/game/AllianceImpl.ts]: this is the same issue: too much logic in game/, this should be inside an execution. Can we put this in alliancerequest execution?

Comment (evanpelle) [reply src/core/game/AllianceImpl.ts]: same with lines 88-98

Comment (deshack) [reply src/core/game/AllianceImpl.ts]: > this is the same issue: too much logic in game/, this should be inside an execution. Can we put this in alliancerequest execution?

Got it, I need to refactor existing codemore ( [here's why](https://github.com/openfrontio/OpenFrontIO/pull/3155#discussion_r2803711267) )

Let me work on it in a moment
