### PR TITLE
Auto transport

### LINKED ISSUE #541: Semi-Automated Transport Launches
## Purpose

Implement semi-automated transport launching.

---

## Objectives

- Attack orders on players without a land border are automatically converted to transport orders.

---

## Description

See Issue #536 for full context, these changes broken out separately for scope creep reasons.

Still has some UI elements that are needed, but the feature works as intended and in the absence of the UI components, the default settings strike a good balance between all the way and all the way off.

---

aPuddle & fake.neo

### PR DESCRIPTION
**Pull request by scottanderson**
## Description:

fixes #541 

## Please complete the following:

- [x] I have added screenshots for all UI updates
- [x] I confirm I have thoroughly tested these changes and take full responsibility for any bugs introduced
- [x] I understand that submitting code with bugs that could have been caught through manual testing blocks releases and new features for all contributors

## Please put your Discord username so you can be contacted if a bug or regression is found:

aPuddle & fake.neo

### CODE REVIEW

File: src/client/ClientGameRunner.ts [hunk 1]
```diff
@@ -359,6 +361,18 @@ export class ClientGameRunner {
             this.myPlayer.troops() * this.renderer.uiState.attackRatio,
           ),
         );
+      } else if (
+        actions.canBoat &&
```
Comment (scottanderson) [inline src/client/ClientGameRunner.ts]: This should be swapped for:

```suggestion
        actions.canBoat !== false &&
```

because the (0,0) tile is falsy

Comment (evanpelle) [reply src/client/ClientGameRunner.ts:365]: 🤮

Comment (evanpelle) [reply src/client/ClientGameRunner.ts]: 🤮

**Review by evanpelle — APPROVED** [review]

**Review by evanpelle — APPROVED** [review]
